import { buildCheckoutUrl, getItemsWithoutId } from '@/services/jumpsellerCart';
import { Link } from 'react-router-dom';
import { Minus, Plus, Trash2, ShoppingCart, ArrowLeft, Zap, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';

const CartPage = () => {
  const { cart, updateCartQty, removeFromCart, cartTotal, clearCart, isB2B, formatDisplayPrice, displayPrice, priceLabel } = useApp();
  
    // cartTotal is always sum of IVA-inclusive prices — derive display total
      const displayTotal = cart.reduce((sum, i) => sum + displayPrice(i.product.price) * i.quantity, 0);
        const ivaAmount = isB2B ? 0 : Math.round(displayTotal - displayTotal / 1.19);
          const neto = isB2B ? displayTotal : Math.round(displayTotal / 1.19);
            const fmt = (n: number) => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', minimumFractionDigits: 0 }).format(n);
            
              // Detectar items sin ID Jumpseller asignado
                const itemsWithoutId = getItemsWithoutId(cart);
                  const hasInvalidItems = itemsWithoutId.length > 0;
                  
                    if (cart.length === 0) {
                        return (
                              <div className="container py-16 text-center">
                                      <ShoppingCart className="h-16 w-16 text-muted-foreground/30 mx-auto mb-4" />
                                              <h1 className="text-2xl font-bold mb-2">Tu carro está vacío</h1>
                                                      <p className="text-muted-foreground mb-6">Explora nuestro catálogo y agrega productos</p>
                                                              <Button asChild className="gradient-primary text-primary-foreground">
                                                                        <Link to="/catalogo">Ver catálogo</Link>
                                                                                </Button>
                                                                                      </div>
                                                                                          );
                                                                                            }
                                                                                            
                                                                                              return (
                                                                                                  <div className="container py-8">
                                                                                                        <Link to="/catalogo" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-primary mb-6 transition-colors">
                                                                                                                <ArrowLeft className="h-4 w-4" />
                                                                                                                        Seguir comprando
                                                                                                                              </Link>
                                                                                                                                    <h1 className="text-2xl font-bold mb-6">Carro de compras</h1>
                                                                                                                                    
                                                                                                                                          {/* Aviso cuando algún producto no tiene jumpseller_id asignado */}
                                                                                                                                                {hasInvalidItems && (
                                                                                                                                                        <div className="mb-4 flex items-start gap-3 rounded-lg border border-yellow-300 bg-yellow-50 px-4 py-3 text-sm text-yellow-800">
                                                                                                                                                                  <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0 text-yellow-600" />
                                                                                                                                                                            <p>
                                                                                                                                                                                        <strong>{itemsWithoutId.map(i => i.product.sku).join(', ')}</strong>{' '}
                                                                                                                                                                                                    {itemsWithoutId.length === 1 ? 'no está disponible' : 'no están disponibles'} para
                                                                                                                                                                                                                compra directa aún. Puedes usar el botón <strong>Cotizar</strong> en su página de
                                                                                                                                                                                                                            producto o contactarnos por WhatsApp.
                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          <div className="grid lg:grid-cols-3 gap-8">
                                                                                                                                                                                                                                                                  <div className="lg:col-span-2 space-y-3">
                                                                                                                                                                                                                                                                            {cart.map(item => (
                                                                                                                                                                                                                                                                                        <div key={item.product.id} className="border rounded-xl p-4 flex gap-4 items-center">
                                                                                                                                                                                                                                                                                                      <div className="h-16 w-16 bg-surface rounded-lg flex items-center justify-center shrink-0 overflow-hidden">
                                                                                                                                                                                                                                                                                                                      {item.product.image ? (
                                                                                                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                                                                                                            src={item.product.image}
                                                                                                                                                                                                                                                                                                                                                                                alt={item.product.name}
                                                                                                                                                                                                                                                                                                                                                                                                    className="h-full w-full object-contain"
                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Zap className="h-8 w-8 text-primary/20" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex-1 min-w-0">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link to={`/producto/${item.product.id}`} className="font-semibold text-sm hover:text-primary transition-colors line-clamp-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.product.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs text-muted-foreground font-mono">{item.product.sku}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-xs text-muted-foreground mt-0.5">{formatDisplayPrice(item.product.price)} c/u {priceLabel}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center border rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="p-1.5 hover:bg-accent transition-colors" onClick={() => updateCartQty(item.product.id, item.quantity - 1)}><Minus className="h-3 w-3" /></button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="px-3 text-sm font-semibold">{item.quantity}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="p-1.5 hover:bg-accent transition-colors" onClick={() => updateCartQty(item.product.id, item.quantity + 1)}><Plus className="h-3 w-3" /></button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="font-bold text-sm w-24 text-right">{fmt(displayPrice(item.product.price) * item.quantity)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => removeFromCart(item.product.id)} className="text-muted-foreground hover:text-destructive transition-colors">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Trash2 className="h-4 w-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="border rounded-xl p-6 h-fit sticky top-32">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="font-bold mb-4">Resumen del pedido</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-2 mb-4 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-muted-foreground">Subtotal neto</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span>{fmt(neto)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-muted-foreground">IVA (19%)</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>{isB2B ? <span className="text-muted-foreground text-xs">facturado aparte</span> : fmt(ivaAmount)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span className="text-muted-foreground">Despacho</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-muted-foreground">Por calcular</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <hr />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex justify-between font-bold text-base">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span>Total {priceLabel}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>{fmt(displayTotal)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {isB2B && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-[11px] text-muted-foreground bg-primary/5 rounded-lg p-2 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Precio neto. IVA (19%) se agrega en la factura: <strong>{fmt(Math.round(displayTotal * 0.19))}</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full gradient-primary text-primary-foreground h-12 text-base gap-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const url = buildCheckoutUrl(cart);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.location.href = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ShoppingCart className="h-4 w-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Ir a comprar en eLights
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-[10px] text-muted-foreground text-center mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Te llevamos a pagar con Webpay en eLights
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default CartPage;import { useApp } from '@/context/AppContext';
import { buildCheckoutUrl } from '@/services/jumpsellerCart';
import { Link } from 'react-router-dom';
import { Minus, Plus, Trash2, ShoppingCart, ArrowLeft, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';

const CartPage = () => {
  const { cart, updateCartQty, removeFromCart, cartTotal, clearCart, isB2B, formatDisplayPrice, displayPrice, priceLabel } = useApp();

  // cartTotal is always sum of IVA-inclusive prices — derive display total
  const displayTotal = cart.reduce((sum, i) => sum + displayPrice(i.product.price) * i.quantity, 0);
  const ivaAmount = isB2B ? 0 : Math.round(displayTotal - displayTotal / 1.19);
  const neto = isB2B ? displayTotal : Math.round(displayTotal / 1.19);
  const fmt = (n: number) => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', minimumFractionDigits: 0 }).format(n);

  if (cart.length === 0) {
    return (
      <div className="container py-16 text-center">
        <ShoppingCart className="h-16 w-16 text-muted-foreground/30 mx-auto mb-4" />
        <h1 className="text-2xl font-bold mb-2">Tu carro está vacío</h1>
        <p className="text-muted-foreground mb-6">Explora nuestro catálogo y agrega productos</p>
        <Button asChild className="gradient-primary text-primary-foreground">
          <Link to="/catalogo">Ver catálogo</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="container py-8">
      <Link to="/catalogo" className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-primary mb-6 transition-colors">
        <ArrowLeft className="h-4 w-4" />
        Seguir comprando
      </Link>
      <h1 className="text-2xl font-bold mb-6">Carro de compras</h1>
      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-3">
          {cart.map(item => (
            <div key={item.product.id} className="border rounded-xl p-4 flex gap-4 items-center">
              <div className="h-16 w-16 bg-surface rounded-lg flex items-center justify-center shrink-0">
                <Zap className="h-8 w-8 text-primary/20" />
              </div>
              <div className="flex-1 min-w-0">
                <Link to={`/producto/${item.product.id}`} className="font-semibold text-sm hover:text-primary transition-colors line-clamp-1">
                  {item.product.name}
                </Link>
                <p className="text-xs text-muted-foreground font-mono">{item.product.sku}</p>
                <p className="text-xs text-muted-foreground mt-0.5">{formatDisplayPrice(item.product.price)} c/u {priceLabel}</p>
              </div>
              <div className="flex items-center border rounded-lg">
                <button className="p-1.5 hover:bg-accent transition-colors" onClick={() => updateCartQty(item.product.id, item.quantity - 1)}><Minus className="h-3 w-3" /></button>
                <span className="px-3 text-sm font-semibold">{item.quantity}</span>
                <button className="p-1.5 hover:bg-accent transition-colors" onClick={() => updateCartQty(item.product.id, item.quantity + 1)}><Plus className="h-3 w-3" /></button>
              </div>
              <p className="font-bold text-sm w-24 text-right">{fmt(displayPrice(item.product.price) * item.quantity)}</p>
              <button onClick={() => removeFromCart(item.product.id)} className="text-muted-foreground hover:text-destructive transition-colors">
                <Trash2 className="h-4 w-4" />
              </button>
            </div>
          ))}
        </div>
        <div className="border rounded-xl p-6 h-fit sticky top-32">
          <h2 className="font-bold mb-4">Resumen del pedido</h2>
          <div className="space-y-2 mb-4 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Subtotal neto</span>
              <span>{fmt(neto)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">IVA (19%)</span>
              <span>{isB2B ? <span className="text-muted-foreground text-xs">facturado aparte</span> : fmt(ivaAmount)}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Despacho</span>
              <span className="text-muted-foreground">Por calcular</span>
            </div>
            <hr />
            <div className="flex justify-between font-bold text-base">
              <span>Total {priceLabel}</span>
              <span>{fmt(displayTotal)}</span>
            </div>
            {isB2B && (
              <p className="text-[11px] text-muted-foreground bg-primary/5 rounded-lg p-2 mt-2">
                Precio neto. IVA (19%) se agrega en la factura: <strong>{fmt(Math.round(displayTotal * 0.19))}</strong>
              </p>
            )}
          </div>
          <Button
            className="w-full gradient-primary text-primary-foreground h-12 text-base gap-2"
            onClick={() => {
              const url = buildCheckoutUrl(cart);
              window.location.href = url;
            }}
          >
            <ShoppingCart className="h-4 w-4" />
            Ir a comprar en eLights
          </Button>
          <p className="text-[10px] text-muted-foreground text-center mt-2">
            Te llevamos a pagar con Webpay en eLights
          </p>
        </div>
      </div>
    </div>
  );
};

export default CartPage;
